### ISSUE TITLE
Vomit stacktrace when unknown command?

### ISSUE THREAD

**Issue by tseemann** [MDU-PHL/LisSero#9]
```
lissero something
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/lissero", line 8, in <module>
    sys.exit(run_lissero())
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/site-packages/lissero/run_lissero.py", line 47, in run_lissero
    path_serodb = os.path.realpath(serotype_db)
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/posixpath.py", line 394, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not NoneType

````

**Comment by andersgs** [comment]
This is now fixed as of commit 90d7cf52a by adding a `requires=True` to the call to the click.argument decorator.
